# Header
menu:
  Home: /
  Archives: /archives

# Title on top left of menu. Leave empty to use main blog title
menu_title: Blockchained India

# URL of the Home page image http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/img/home-bg.jpg
index_cover: http://static.webwereld.nl/uploads/f/o/for89a6aa8zejacg.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: blockchainedindia
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-98002907-2

# Addthis ID
addthis:

# set your own favicon
favicon: img/favicon.ico

# Social Accounts
twitter_url: https://twitter.com/blockchainedind?lang=en
facebook_url: https://www.facebook.com/blockchainedindia
twitter_handle: blockchainedind
# github_url: https://github.com/blockchainedindia
mailto: contact@blockchainedindia.com
