# Logo (Font Awesome Class)
fa_logo: fa-chain

# Header
menu:
  Home: /
  Archives: /archives
#  About: /about.html
#  Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/blockchainedind?lang=en
facebook_url: https://www.facebook.com/blockchainedindia
#instagram_url: https://www.instagram.com/blockchainedindia
#dribble_url: https://dribbble.com/
github_url: https://github.com/blockchainedindia/blog
#googleplus_url: https://plus.google.com/
#behance_url: https://www.behance.net/
#fivehundredpx_url: https://500px.com/
email_url: contact@blockchainedindia.com
#rss_url: \#

# Footer About Text
footer_about: "Join Us - Blockchained India."

# Footer Copyright Line
footer_copyright: "Maintained by Blockchained India Community"

